use rust_affected::lockfile::compute_lockfile_diff;
use std::collections::HashSet;

fn members<'a>(names: &'a [&'a str]) -> Vec<&'a str> {
    names.to_vec()
}

fn set(names: &[&str]) -> HashSet<String> {
    names.iter().map(|s| s.to_string()).collect()
}

// ── Fixture: an 8-crate workspace mirroring tests/fixtures/workspace/ ──
//
// app-alpha     → lib-core → lib-utils
// app-beta      → lib-core, lib-standalone
// lib-core-ext  → lib-core
// tool-alpha    → lib-utils
// lib-standalone, lib-utils, lib-with-tests: leaves
fn workspace_lockfile_basic() -> String {
    r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app-alpha"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "app-beta"
version = "0.1.0"
dependencies = [
 "lib-core",
 "lib-standalone",
]

[[package]]
name = "lib-core"
version = "0.1.0"
dependencies = [
 "lib-utils",
]

[[package]]
name = "lib-core-ext"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "lib-standalone"
version = "0.1.0"

[[package]]
name = "lib-utils"
version = "0.1.0"

[[package]]
name = "lib-with-tests"
version = "0.1.0"

[[package]]
name = "tool-alpha"
version = "0.1.0"
dependencies = [
 "lib-utils",
]
"#
    .to_string()
}

fn all_members() -> Vec<&'static str> {
    members(&[
        "app-alpha",
        "app-beta",
        "lib-core",
        "lib-core-ext",
        "lib-standalone",
        "lib-utils",
        "lib-with-tests",
        "tool-alpha",
    ])
}

// ── No-op: identical lockfile ───────────────────────────────────────

#[test]
fn identical_lockfiles_produce_empty_set() {
    let lock = workspace_lockfile_basic();
    let diff = compute_lockfile_diff(&lock, &lock, &all_members());
    assert!(diff.fallback_reason.is_none());
    assert!(diff.affected_members.is_empty());
}

// ── Pure version-header bump, no package diff ───────────────────────

#[test]
fn version_header_only_change_is_empty() {
    let old = workspace_lockfile_basic();
    let new = old.replace("version = 4", "version = 3");
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    assert!(diff.affected_members.is_empty());
}

// ── External registry dep added to a leaf workspace member ──────────

#[test]
fn external_dep_added_to_leaf_affects_chain() {
    let old = workspace_lockfile_basic();
    // Add `serde` as a transitive dep of `lib-utils`. Everyone reaching
    // lib-utils should be affected.
    let new = old.replace(
        r#"[[package]]
name = "lib-utils"
version = "0.1.0"
"#,
        r#"[[package]]
name = "lib-utils"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000001"
"#,
    );
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    // Everyone reaching lib-utils: lib-utils, lib-core, lib-core-ext,
    // app-alpha, app-beta (via lib-core), tool-alpha.
    // lib-standalone, lib-with-tests are NOT affected.
    assert_eq!(
        diff.affected_members,
        set(&[
            "lib-utils",
            "lib-core",
            "lib-core-ext",
            "app-alpha",
            "app-beta",
            "tool-alpha",
        ])
    );
}

// ── External registry dep version bumped ────────────────────────────

#[test]
fn external_dep_version_bump_affects_dependents() {
    let prefix = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app-alpha"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "app-beta"
version = "0.1.0"
dependencies = [
 "lib-core",
 "lib-standalone",
]

[[package]]
name = "lib-core"
version = "0.1.0"
dependencies = [
 "lib-utils",
 "serde",
]

[[package]]
name = "lib-core-ext"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "lib-standalone"
version = "0.1.0"

[[package]]
name = "lib-utils"
version = "0.1.0"

[[package]]
name = "lib-with-tests"
version = "0.1.0"

[[package]]
name = "tool-alpha"
version = "0.1.0"
dependencies = [
 "lib-utils",
]

[[package]]
name = "serde"
"#;
    let old = format!(
        "{prefix}version = \"1.0.200\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"0000000000000000000000000000000000000000000000000000000000000001\"\n"
    );
    let new = format!(
        "{prefix}version = \"1.0.201\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"0000000000000000000000000000000000000000000000000000000000000002\"\n"
    );
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    // serde is a transitive dep of lib-core. Affected: lib-core, lib-core-ext,
    // app-alpha (→ lib-core), app-beta (→ lib-core).
    assert_eq!(
        diff.affected_members,
        set(&["lib-core", "lib-core-ext", "app-alpha", "app-beta"])
    );
}

// ── Checksum-only change (yanked re-upload) ─────────────────────────

#[test]
fn checksum_only_change_is_detected() {
    let prefix = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app-alpha"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "app-beta"
version = "0.1.0"
dependencies = [
 "lib-core",
 "lib-standalone",
]

[[package]]
name = "lib-core"
version = "0.1.0"
dependencies = [
 "lib-utils",
]

[[package]]
name = "lib-core-ext"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "lib-standalone"
version = "0.1.0"

[[package]]
name = "lib-utils"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "lib-with-tests"
version = "0.1.0"

[[package]]
name = "tool-alpha"
version = "0.1.0"
dependencies = [
 "lib-utils",
]

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = ""#;
    let old =
        format!("{prefix}0000000000000000000000000000000000000000000000000000000000000001\"\n");
    let new =
        format!("{prefix}0000000000000000000000000000000000000000000000000000000000000002\"\n");
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    // serde reachable from lib-utils; affects whole chain.
    assert_eq!(
        diff.affected_members,
        set(&[
            "lib-utils",
            "lib-core",
            "lib-core-ext",
            "app-alpha",
            "app-beta",
            "tool-alpha",
        ])
    );
}

// ── External dep removed from a member ──────────────────────────────

#[test]
fn external_dep_removed_affects_dependents() {
    let old = workspace_lockfile_basic().replace(
        r#"[[package]]
name = "lib-standalone"
version = "0.1.0"
"#,
        r#"[[package]]
name = "lib-standalone"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000001"
"#,
    );
    let new = workspace_lockfile_basic();
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    // serde was reachable only from lib-standalone (→ app-beta).
    assert_eq!(diff.affected_members, set(&["lib-standalone", "app-beta"]));
}

// ── Multi-version of same external crate ────────────────────────────

#[test]
fn multi_version_disambiguation_works() {
    // lib-core depends on serde v1, tool-alpha depends on serde v2.
    // Bumping serde v1 only should affect lib-core's reverse chain;
    // tool-alpha should be unaffected.
    let template = |v1_checksum: &str| {
        format!(
            r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app-alpha"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "app-beta"
version = "0.1.0"
dependencies = [
 "lib-core",
 "lib-standalone",
]

[[package]]
name = "lib-core"
version = "0.1.0"
dependencies = [
 "lib-utils",
 "serde 1.0.200",
]

[[package]]
name = "lib-core-ext"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "lib-standalone"
version = "0.1.0"

[[package]]
name = "lib-utils"
version = "0.1.0"

[[package]]
name = "lib-with-tests"
version = "0.1.0"

[[package]]
name = "tool-alpha"
version = "0.1.0"
dependencies = [
 "lib-utils",
 "serde 2.0.0",
]

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "{v1_checksum}"

[[package]]
name = "serde"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000002"
"#
        )
    };
    let old = template("0000000000000000000000000000000000000000000000000000000000000001");
    let new = template("000000000000000000000000000000000000000000000000000000000000000a");
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    // Only the serde v1 reverse chain is affected (lib-core, dependents).
    assert_eq!(
        diff.affected_members,
        set(&["lib-core", "lib-core-ext", "app-alpha", "app-beta"])
    );
}

// ── Workspace member version bump ────────────────────────────────────

#[test]
fn workspace_member_version_bump_affects_dependents() {
    let old = workspace_lockfile_basic();
    let new = old.replace(
        r#"[[package]]
name = "lib-utils"
version = "0.1.0"
"#,
        r#"[[package]]
name = "lib-utils"
version = "0.2.0"
"#,
    );
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    // lib-utils version changed; every workspace member reaching it has a
    // different transitive set.
    assert_eq!(
        diff.affected_members,
        set(&[
            "lib-utils",
            "lib-core",
            "lib-core-ext",
            "app-alpha",
            "app-beta",
            "tool-alpha",
        ])
    );
}

// ── Workspace member added in new only ──────────────────────────────

#[test]
fn workspace_member_added_in_new_is_skipped() {
    let old = workspace_lockfile_basic();
    let new = format!("{old}\n[[package]]\nname = \"lib-brand-new\"\nversion = \"0.1.0\"\n");
    let members = members(&[
        "app-alpha",
        "app-beta",
        "lib-core",
        "lib-core-ext",
        "lib-standalone",
        "lib-utils",
        "lib-with-tests",
        "tool-alpha",
        "lib-brand-new",
    ]);
    let diff = compute_lockfile_diff(&old, &new, &members);
    assert!(diff.fallback_reason.is_none());
    // No existing member's transitive set changed; lib-brand-new is silently
    // skipped (the file-based path catches its newly-added Cargo.toml).
    assert!(diff.affected_members.is_empty());
}

// ── Workspace member removed (in old, not new) ──────────────────────

#[test]
fn workspace_member_removed_does_not_panic() {
    let new = workspace_lockfile_basic();
    let old = format!("{new}\n[[package]]\nname = \"lib-gone\"\nversion = \"0.1.0\"\n");
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    assert!(diff.affected_members.is_empty());
}

// ── Git dep revision bump ──────────────────────────────────────────

#[test]
fn git_dep_revision_bump_is_detected() {
    let prefix = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app-alpha"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "app-beta"
version = "0.1.0"
dependencies = [
 "lib-core",
 "lib-standalone",
]

[[package]]
name = "lib-core"
version = "0.1.0"
dependencies = [
 "lib-utils",
 "remote-git-dep",
]

[[package]]
name = "lib-core-ext"
version = "0.1.0"
dependencies = [
 "lib-core",
]

[[package]]
name = "lib-standalone"
version = "0.1.0"

[[package]]
name = "lib-utils"
version = "0.1.0"

[[package]]
name = "lib-with-tests"
version = "0.1.0"

[[package]]
name = "tool-alpha"
version = "0.1.0"
dependencies = [
 "lib-utils",
]

[[package]]
name = "remote-git-dep"
version = "0.1.0"
source = "git+https://example.test/repo.git?rev="#;
    let old = format!(
        "{prefix}aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n"
    );
    let new = format!(
        "{prefix}bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb#bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\"\n"
    );
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    // remote-git-dep is reachable from lib-core; affects its chain.
    assert_eq!(
        diff.affected_members,
        set(&["lib-core", "lib-core-ext", "app-alpha", "app-beta"])
    );
}

// ── Malformed lockfile → fallback ────────────────────────────────────

#[test]
fn malformed_lockfile_sets_fallback_reason() {
    let old = "not a real lockfile";
    let new = workspace_lockfile_basic();
    let diff = compute_lockfile_diff(old, &new, &all_members());
    assert!(diff.fallback_reason.is_some());
    assert!(diff.affected_members.is_empty());
}

#[test]
fn malformed_new_lockfile_sets_fallback_reason() {
    let old = workspace_lockfile_basic();
    let new = "{ also not a lockfile }";
    let diff = compute_lockfile_diff(&old, new, &all_members());
    assert!(diff.fallback_reason.is_some());
    assert!(diff.affected_members.is_empty());
}

// ── Isolated change only affects its dependent ──────────────────────

#[test]
fn change_to_lib_standalone_only_affects_app_beta() {
    let old = workspace_lockfile_basic();
    // Add a dep only to lib-standalone.
    let new = old.replace(
        r#"[[package]]
name = "lib-standalone"
version = "0.1.0"
"#,
        r#"[[package]]
name = "lib-standalone"
version = "0.1.0"
dependencies = [
 "anyhow",
]

[[package]]
name = "anyhow"
version = "1.0.80"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000003"
"#,
    );
    let diff = compute_lockfile_diff(&old, &new, &all_members());
    assert!(diff.fallback_reason.is_none());
    // Only lib-standalone and its sole dependent app-beta.
    assert_eq!(diff.affected_members, set(&["lib-standalone", "app-beta"]));
}
